describe('Hari Ke 4 ', function(){

        it ('Pembelian',function(){
            cy.BukaUrl()
            cy.get('#login2').click()
            cy.wait(1000)
            cy.get('#loginusername').type("zaraki").should('have.value','zaraki')
            cy.get('#loginpassword').type('indonesia12').should('have.value','indonesia12')
            cy.get('#logInModal > .modal-dialog > .modal-content > .modal-footer > .btn-primary').click()
            // cy.wait(1000)
            // cy.get(':nth-child(1) > .card > :nth-child(1) > .card-img-top').click()
            cy.wait(1000)
            cy.get(':nth-child(1) > .card > .card-block > .card-title > .hrefch').click()
            cy.contains('Add to cart').click().should('exist')
            cy.wait(500)
            cy.get('.navbar-nav > .active').click()
            cy.get(':nth-child(2) > .card > .card-block > .card-title > .hrefch').click()
            cy.contains('Add to cart').click().should('exist')
            cy.get('.navbar-nav > .active').click()
            cy.contains('Cart').click()
            cy.wait(1000)
            cy.get('.col-lg-1 > .btn').click()
            cy.wait(1000)
            cy.get('#name').type('tuan takur').should('have.value','tuan takur')
            cy.get('#country').type('prindapan').should('have.value','prindapan')
            cy.get('#city').type('zimbabwe').should('have.value','zimbabwe')
            cy.get('#card').type('12321414').should('have.value','12321414')
            cy.get('#month').type('Agustus').should('have.value','Agustus')
            cy.get('#year').type('2020').should('have.value','2020')
            cy.get('#orderModal > .modal-dialog > .modal-content > .modal-footer > .btn-primary').click()
            cy.wait(3000)
            cy.get('.confirm').click()
        })
})
